# Generated by Django 5.2.7 on 2025-10-30 18:00

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_add_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="project",
            new_name="projects_pr_is_publ_39fbeb_idx",
            old_name="proj_pub_feat_order_idx",
        ),
        migrations.RenameIndex(
            model_name="project",
            new_name="projects_pr_is_publ_e7dcb8_idx",
            old_name="proj_pub_ord_comp_idx",
        ),
        migrations.RenameIndex(
            model_name="project",
            new_name="projects_pr_categor_d31906_idx",
            old_name="proj_cat_pub_idx",
        ),
        migrations.RenameIndex(
            model_name="technology",
            new_name="projects_te_categor_f164b4_idx",
            old_name="tech_cat_prof_idx",
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="#ff6b35",
                max_length=7,
                validators=[projects.models.validate_hex_color],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="completed_at",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Project completion date",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Show on homepage"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Publish this project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.IntegerField(
                db_index=True, default=0, help_text="Display order (0 = first)"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="primary_color",
            field=models.CharField(
                default="#ff6b35",
                help_text="Primary HEX color",
                max_length=7,
                validators=[projects.models.validate_hex_color],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="secondary_color",
            field=models.CharField(
                default="#f7931e",
                help_text="Secondary HEX color",
                max_length=7,
                validators=[projects.models.validate_hex_color],
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="order",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="technology",
            name="color",
            field=models.CharField(
                default="#ff6b35",
                help_text="HEX color for badges",
                max_length=7,
                validators=[projects.models.validate_hex_color],
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="order",
            field=models.IntegerField(
                db_index=True, default=0, help_text="Display order"
            ),
        ),
    ]
