# Generated by Django 5.2.7 on 2025-11-03 05:13

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0004_rename_proj_pub_feat_order_idx_projects_pr_is_publ_39fbeb_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="primary_color",
            field=models.CharField(
                default="#95ff17",
                help_text="Primary HEX color",
                max_length=7,
                validators=[projects.models.validate_hex_color],
            ),
        ),
    ]
