name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  DJANGO_SETTINGS_MODULE: "portfolio_dimitri.settings"
  SECRET_KEY: "ci-secret-key"
  DEBUG: "False"
  ENVIRONMENT: "production"
  ALLOWED_HOSTS: "127.0.0.1,localhost,dim-gggl.com,www.dim-gggl.com"
  SITE_URL: "https://dim-gggl.com"
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test_portfolio"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/dev.txt
            requirements/prod.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Run Black
        run: black --check .

      - name: Run Flake8
        run: flake8

  tests:
    name: Django Tests
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_portfolio
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
          pip install -r requirements/prod.txt

      - name: Django health checks
        run: |
          python manage.py check --fail-level=ERROR
          python manage.py makemigrations --check --dry-run

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

  build_static:
    name: Build Static Assets
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/prod.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/prod.txt

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Compress assets
        run: python manage.py compress --force

  build_docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build_static
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dim-gggl-site:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/dim-gggl-site:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

